server:
  port: 63040

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.88.129:3230/db_mybatis?serverTimezone=UTC
    username: root
    password: 1234567890
logging:
  config: classpath:log4j2-dev.xml
  file:
    path: logs/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fe.blog.bean