server:
  port: 1633

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.43.49:3230/db_mybatis?serverTimezone=UTC
    username: root
    password: 1234567890
logging:
  level:
    root: info
    org.springframework.web: info
    org.apache: info
  logback:
    rollingpolicy:
      max-file-size: 1MB
  file:
    path: logs/
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fe.blog.bean